// <auto-generated />
namespace NCSolution.Migrations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add2feildstoLoginuser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add2feildstoLoginuser));
        
        string IMigrationMetadata.Id
        {
            get { return "201705021931219_add2feildstoLoginuser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
