// <auto-generated />
namespace NCSolution.Migrations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class question_image_model_AuditableEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(question_image_model_AuditableEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "201704282201527_question_image_model_AuditableEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
