// <auto-generated />
namespace NCSolution.Migrations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class userloginExamsdata_insert : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userloginExamsdata_insert));
        
        string IMigrationMetadata.Id
        {
            get { return "201705030918426_userloginExamsdata_insert"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
